import { useState, type FormEvent } from 'react'
import { CheckCircle2, Clock3, GitBranch, ShieldCheck, TrendingUp, AlertTriangle } from 'lucide-react'
import { Layout, SignalBar } from '../components/layout'
import { Badge } from '../components/ui/badge'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card'
import { Input } from '../components/ui/input'
import { Select } from '../components/ui/select'
import { useI18n } from '../providers/i18n-provider'
import { z } from 'zod'

const signalSchema = z.object({ branch: z.string().min(2), files: z.coerce.number().int().min(1).max(500), duration: z.coerce.number().min(1).max(180) })
export function Dashboard() {
  const { t } = useI18n(); const [values, setValues] = useState({ branch: 'release/august-24', files: '14', duration: '18' }); const [saved, setSaved] = useState(false)
  const files = Number(values.files); const duration = Number(values.duration); const score = Math.max(0, Math.min(99, 94 - Math.round(files * 0.8) - Math.round(duration / 12)); const isReady = score >= 78
  function submit(event: FormEvent) { event.preventDefault(); const result = signalSchema.safeParse(values); if (result.success) { setSaved(true); window.setTimeout(() => setSaved(false), 2400) } }
  return <Layout><section className="mb-8 pt-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Badge><Activity size={13} className="ltr:mr-1 rtl:ml-1"/> {t('lastChecked')}</Badge><h1 className="mt-4 text-3xl font-bold tracking-tight md:text-4xl">{t('dashboard')}</h1><p className="mt-2 text-slate-500 dark:text-slate-400">{t('subtitle')}</p></div><Button onClick={() => setSaved(true)}><TrendingUp size={17}/>{t('update')}</Button></div></section>
    <div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><Card className="overflow-hidden bg-ink text-white dark:bg-white/[0.06]"><CardContent className="p-6 md:p-8"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{t('readiness')}</p><div className="mt-3 flex items-baseline gap-2"><span className="text-7xl font-bold tracking-tighter text-mint">{score}</span><span className="text-xl text-slate-400">/100</span></div></div><div className={`rounded-full p-3 ${isReady ? 'bg-mint/15 text-mint' : 'bg-amber/15 text-amber'}`}>{isReady ? <CheckCircle2 size={28}/> : <AlertTriangle size={28}/>}</div></div><div className="mt-8"><div className="mb-2 flex justify-between text-xs text-slate-400"><span>DECISION ENGINE</span><span>{isReady ? t('ready') : t('investigate')}</span></div><div className="h-3 rounded-full bg-white/10"><div className={`h-full rounded-full ${isReady ? 'bg-mint' : 'bg-amber'}`} style={{ width: `${score}%` }}/></div></div></CardContent></Card>
      <Card><CardHeader><CardTitle>{t('signals')}</CardTitle><CardDescription>Weighted from your latest pipeline telemetry</CardDescription></CardHeader><CardContent className="space-y-5"><SignalBar label={t('changeRisk')} value={82} color="bg-amber"/><SignalBar label={t('testConfidence')} value={96}/><SignalBar label={t('rollback')} value={88}/><SignalBar label={t('health')} value={99}/></CardContent></Card></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle>{t('release')}</CardTitle><CardDescription>Signals are validated before scoring.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">{t('branch')}<Input className="mt-2" value={values.branch} onChange={e => setValues({ ...values, branch: e.target.value })}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">{t('files')}<Input className="mt-2" type="number" value={values.files} onChange={e => setValues({ ...values, files: e.target.value })}/></label><label className="block text-sm font-medium">{t('duration')}<Select className="mt-2" value={values.duration} onChange={e => setValues({ ...values, duration: e.target.value })}><option value="8">8 minutes</option><option value="18">18 minutes</option><option value="35">35 minutes</option></Select></label></div><Button type="submit" className="w-full">{saved ? <><CheckCircle2 size={16}/>{t('saved')}</> : t('save')}</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>Why this score?</CardTitle><CardDescription>Decision context for the on-call engineer</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex gap-3 rounded-xl bg-mint/10 p-4"><ShieldCheck className="shrink-0 text-ocean dark:text-mint" size={20}/><div><p className="font-semibold">Coverage is protecting the change</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Your 96% test confidence offsets the medium-sized change set.</p></div></div><div className="flex gap-3 rounded-xl bg-amber/10 p-4"><Clock3 className="shrink-0 text-amber" size={20}/><div><p className="font-semibold">Rollback rehearsal is fresh</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">The previous rollback completed in 4m 12s, under your 10-minute policy.</p></div></div><div className="flex gap-3 rounded-xl bg-slate-100 p-4 dark:bg-white/5"><GitBranch className="shrink-0 text-slate-500" size={20}/><div><p className="font-semibold">Branch is release protected</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Required approvals and signed artifacts are present.</p></div></div></CardContent></Card></div>
  </Layout>
}